### ISSUE TITLE
Problem with loading wav

### ISSUE THREAD

**Issue by kiFlaFlaki** [MiSTer-devel/Orao_MiSTer#1]
I have problem when loading wav files to Orao. After new MiSTer update (MiSTer v200225), while loading wav there is new progress bar which obviously interfere with loading sound (progress bar drawing makes audible "click" sound every second which broke audio file, so Orao can't load program properly (at all).

**Comment by sorgelig** [comment]
Core uses file loading as stream with pauses which is quite unusual. This part needs to be rewritten to use either SDRAM or DDR3 memory as a buffer.

**Comment by hrvach** [comment]
Hi there! I will definitely take a look and try fixing it. As a side note - I recently changed countries and jobs, so I don't have my usual setup and it will probably take me a bit longer. Hope to get it sorted out soon!

**Comment by kiFlaFlaki** [comment]
Great, thanks!

**Comment by hrvach** [comment]
Managed to find a few mins and fixed the issue using a loading buffer. It uses smaller and more efficient .tap files now (included in repo).

Simply load the .tap file through the F12 menu into the loading buffer first and type LMEM ""

Have fun!

**Comment by kiFlaFlaki** [comment]
Great, it works now! Only missing loading sound but otherwise great!
Thanks!

**Comment by hrvach** [comment]
Didn't have headphones nearby. Loading sound fixed. :)

**Comment by kiFlaFlaki** [comment]
WOW! Great, now works fantastic! Thanks!
